version: '1.0'
stages:
  - prepare
  - test
  - build
steps:
  main_clone:
    title: Cloning main repository...
    stage: prepare
    type: git-clone
    repo: 'react-article-display'
    revision: master
    git: github
  MyUnitTests:
    title: Unit test
    stage: test
    image: node:8.16
    commands:
      - yarn install
      - yarn test
    environment:
      - CI=true
  MyAppDockerImage:
    title: Building Docker Image
    type: build
    stage: build
    image_name: react-article-display
    working_directory: ./
    tag: 'with-nginx'
    dockerfile: Dockerfile
  PushToDockerRegistry:
    type: push
    candidate: '${{BuildImage}}'
    tag: '${{CF_BRANCH_TAG_NORMALIZED}}'
    registry: 'docker-account'
  StoreChart:
    title: Storing Helm Chart
    type: helm
    stage: store
    working_directory: ./
    arguments:
      action: push
      chart_name: charts
      kube_context: digitalOcean@k8s-1-18-6-do-0-fra1-1598889669983
  DeployChart:
    type: helm
    stage: deploy
    working_directory: ./
    arguments:
      action: install
      chart_name: charts
      release_name: first
      helm_version: 3.0.2
      kube_context: digitalOcean@k8s-1-18-6-do-0-fra1-1598889669983