version: "1.0"

stages:
  - "clone"
  - "build"
  - "test"
  - "store"
  
steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "AnaisUrlichs/react-article-display"
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  build:
    title: "Building Docker image"
    type: "build"
    image_name: "anaisurlichs/react-article-display"
    working_directory: "${{clone}}"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
    dockerfile: "Dockerfile"
    stage: "build"

  test:
    title: "Running test"
    type: "freestyle"
    image: "ubuntu:latest"
    working_directory: "${{clone}}"
    commands:
      - "ls"
    stage: "test"

  deploy:
    type: "helm"
    arguments:
      action: "install"
      chart_name: "charts"
      release_name: "first"
      helm_version: 3.0.1
      kube_context: "digitalOcean@k8s-1-18-6-do-0-fra1-1598889669983"